version: "3.7"

services:
  unit:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../api:/home/user/api

  integration:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../api:/home/user/api
