version: "3.7"

services:
  unit:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../app:/app/app

  integration:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../app:/app/app
